# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20170922_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='answer',
            new_name='status',
        ),
    ]
